# Don't print a new line at the start of the prompt
add_newline = false
# format = "$shell $all"
format = """
$shell \
$directory\
$git_branch\
$git_status\
\r
$character
"""

[character] # The name of the module we are configuring is "character"
success_symbol = "[→](bold green)" # The "symbol" segment is being set to "➜"
error_symbol = "[×](bold red)"

[directory]
truncation_length = 12
truncation_symbol = "…/"
use_os_path_sep = false

[shell]
disabled = false
nu_indicator = "NU"
bash_indicator = "BS"
zsh_indicator = "ZSH"
powershell_indicator = "PS"
format = "[$indicator]($style)"

[git_branch]
symbol = ' '
